language: ruby

rvm:
  - 2.4.0

cache: bundler

install:
  - bundle install

before_script:
  - "chmod +x ./build.sh"

script:
  "./build.sh"

branches:
  only:
    - gh-pages-edit

env:
  global:
    secure: "pXWhDYN0NowgBnO8z+CMTHj9Ojob1YeDT7DEPMXUpWGNg9VzQ1ysY2N1EarIS95sg/CAz6eeq/YfnBnTqwHxqFp+Rt4ks7IQ3nMs+FOq+FieuHhEbH7KI/Asvgh6NcpHN8zCsXFFnFdCaAGgh1jy1jLl1KQaCq7seRWVD9MKoa5AYrShpJUwwjqvrO2T7ng0ES9ktG6TZbbto5bfYd1EequcuGFYY6XX/001BetBgcQugth7HavRwR9F+nXeqlStXUyPIQ/ELsGvpGnPOZpJbU6eck7wcriapKPopglrjvKH0Upob1BfjNuUc5NzPbwEcUxX1ddex5XDq6VSFEoFKVutp4rVMHLEHtz21oRmpZf1VEJoNwY+5TW+5ghgyn4N5vCRA3rPOElrpm/V2xLCNrmbfXThTxITvIas0rb/4eDgC1GNSFe6HTM+WHnp+v47SjOLjAFBLIDMwVupCbm71wju5NA3PpqKI/3xe3OrgVahvoacMMtcTI39UVrReH3MhLwyd/bzSYIyj5WTQHcelSmOJ8FZQKQ5DZpa8ol15r7Y8dsEb7MG9p/cO4c2nilnHsUWa6V7OpTsFWZqFFwgSMwh/EoAHLcyny3jkYz0FzXVtLtDuTO4yDqy626aDaIfwjgnmYD5QEeiqVJkr7myrDmFiljMgqcsKsGMb/sRmP4="
