language: ruby

rvm:
  - 2.4.0

cache: bundler

install:
  - bundle install

before_script:
  - "chmod +x ./build.sh"

script:
  "./build.sh"

branches:
  only:
    - gh-pages-edit

env:
  global:
    secure: "tTKX9E9ZR3nmsVsktdYB6NvozeixqMnPUj01FsC5kUAvUYwgAUjlMsU87JZa8Z78KyAP0SY8VCPPpE4s510I7V1nxDhLWzn0732Vza+lCLo80JV9b85+g8xv/uGVUB9SC49NTBVRcW0gU/rcQoOv7W1BtDyNMXn1sMTr1vzgEoIsocpF8RKDi6PJTPs70QaT1YPiCq8n+qTTUPK+kf5sCLUuzb6JvwNJDV2cfKoekJqa09dsTK4PShu9ah17dsU15DJm5+57rzgaQbvQc/AJtKPgSqxb3Q5nNnGQCfShq/9grS/Glpo8znnC1pYyff82AcoBdP1HPC9RR+kQrRGhILMYnf1RAIHnrF23U7txJa50XBDNzd/9hnLv5UP0tUoqqvwK03KtGyqZAtzVtJdYVNCsQ+0lT4cepLduMo9BTInjYgNno52YaZ5ybOdPp5ScT0zijsJqWkCt/3mGHVHZYlyuhBoqSCx37mk4ywkRKKwfha6G19+/WkQKMxVE4z5946pN4eAQ1oODVdLmcepbS6MyxiXJmdmNfZnk4jR7ctw4XWaME1KLtJRcg0nex/FO44PB+YQvrY84okQQ1HQbFAe9JnYIzvocmYhY0/6sKDbty4hoPgfRlzJJsj0OGMHogfyu0+Uz44zii8kVT4qSdhe1pzMyc/DIQS2v95r8x54="
