language: ruby

rvm:
  - 2.4.0

cache: bundler

install:
  - bundle install

before_script:
  - "chmod +x ./build.sh"

script:
  "./build.sh"

branches:
  only:
    - gh-pages-edit

env:
  global:
    secure: "FR/6j3Ky6NLeY1QrfXjF3gB0Ji/KMWukfq7/AxVzLYmcX9TC7YbIqjOdsblh/pJolI4B1RfFcDBSUO2m1Ak63ZtpxSHGuYxXLhUV2eAvloPh6ibRdEgML78Yu+6HRpgZ9mH3wRUAYQ/Sjmy6ZJmYCOyfw/aut3LTfLbJcfAWW0sQ1D85sc37Sj5rbLpBAPBSAzN5tgcw4oQaKol6xVOgQS6BeAyamCkCPrKt91CWjDh4om6v55g5NoP/guEDsNNPxwuEZu2nrKykuo7BwCPjBFUClnGhzMMrmw0kSB1+ErCfSzmsfBQBEiuD0Y6Pha+ufbYwph8JX+pMayC/kVc4QeA4RiZe3Z8ujeILB9FrGdAucukYW4zs+1B7ARzE5uTrRwfkP2jCxmxmdUKQ3aaeiSYdww2ZAYcT5a9cYiAa9cQHoXqbRLH/Lr/bzZjjS264Ie2w54Kb+ItDGJIBl8TU+sKvqVuWY+QnEvpFKQ57XJ535ckPVqB+xjI6k2AiZydMZJ18IXfV5sgbWwuas/zbKxvS2i8o6k1YTqdbKaED56YOjCACBdxL8ZVLxnRmfwlHMq5R1/bqBikFUkxOV9eQgWmNmLll89em8+0cfEd141wbgA8B1XoIkT9qWiTAu0TVgCyP5oma2nTkTtHiVfxpE228sKM+BtPAsi4bEgOrIvU="
