# Site settings
title: The GEMOC Initiative
email: contact@gemoc.org
description: > # this means to ignore newlines until "baseurl:"
  GEMOC develops techniques, frameworks, and environments to facilitate the creation, integration, and automated processing of heterogeneous modeling languages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gemoc.github.io/website" # the base hostname & protocol for your site
twitter_username: gemocinitiative
github_username:  gemoc

# Build settings
markdown: kramdown

# These override Jekyll defaults
# permalink: /:year/:title

# These are new (in addition to Jekyll's elements above )
organization: The GEMOC Initiative
#placeholderimagesbaseurl: http://placehold.it/

