# Site settings
title: The GEMOC Initiative
email: contact@gemoc.org
description: > # this means to ignore newlines until "baseurl:"
  GEMOC develops techniques, frameworks, and environments to facilitate the creation, integration, and automated processing of heterogeneous modeling languages.
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "https://gemoc.github.io" # the base hostname & protocol for your site
twitter_username: gemocinitiative
github_username:  gemoc

# Build settings
markdown: kramdown

# These override Jekyll defaults
# permalink: /:year/:title

exclude: [vendor]

# These are new (in addition to Jekyll's elements above )
organization: The GEMOC Initiative
#placeholderimagesbaseurl: http://placehold.it/

gems:

# jekyll-scholar configurations
scholar:
  style: ./publications/acm-sig-proceedings-long-author-list.csl
  use_raw_bibtex_entry : true
  locale: en
  sort_by: year
  order: descending
  source: ./publications
  bibliography: gemoc.bib
  details_dir: ./publications/details
  query: "@*[public!=no]"

  # Scholar has changed the way it renders bib tags
  # Need to look at more at the defaults.
  #bibliography_list_tag: "ul"
